name: Publish PyPI

on:
  release:
    types:
      - published

jobs:

  publish:
    name: Publish Release
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - run: sudo apt-get install -y gcc libomp-dev libopenblas-dev

      - run: make env_uv

      - name: Build package
        run: make build

      - name: Publish package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make upload
