name: Test Ubuntu

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Testing ${{matrix.os}} py-${{matrix.python-version}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - run: sudo apt-get install -y gcc libomp-dev libopenblas-dev

      - run: make env_uv python_version=${{ matrix.python-version }}

      - run: make test
      - run: make format
      - run: make build
      - run: make test-dist
